name: Telegram Notification
'on':
  push:
    branches:
      - "*"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
